# Modeling in R


```{r setup5, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse=TRUE, tidy.opts=list(width.cutoff=60),
                      warning=FALSE, message=FALSE, tidy=F)
```



<div style="margin-bottom:40px;">
</div>

><left>**LEARNING OUTCOMES**</left>
><div style="margin-bottom:30px;">
></div>
>- Identify the capabilities of R and RStudio's environment and appraise their functionality.
>- Distinguish between R functions, objects, and diverse data wrangling approaches.
>- Apply basic programming skills to import and organize the data using classic data wrangling approaches and the **tidyverse** grammar.
>- Evaluate the R code and appraise the outputs to demonstrate a satisfactory level of basic programming skills in R.



<div style="margin-bottom:60px;">
</div>


The purpose of a statistical model is to help understand what variables might best predict a phenomenon of interest, which ones have more or less influence, define a predictive equation with coefficients for each of the variables, and then apply that equation to predict values using the same input variables for other areas. This process requires samples with observations of the explanatory (or independent) and response (or dependent) variables in question.



## Some common statistical models

There are many types of statistical models. Variables may be nominal (categorical) or interval/ratio data. You may be interested in predicting a continuous interval/ratio variable from other continuous variables, or predicting the probability of an occurrence (e.g. of a species), or maybe the count of something (also maybe a species). You may be needing to classify your phenomena based on continuous variables. Here are some examples:

- `lm(y ~ x)` linear regression model with one explanatory variable
- `lm(y ~ x1 + x2 + x3)` multiple regression, a linear model with multiple explanatory variables
- `glm(y ~ x, family = poisson)` generalized linear model, poisson distribution; see ?family to see those supported, including binomial, gaussian, poisson, etc.
- `glm(y ~ x + y, family = binomial)` glm for logistic regression
- `aov(y ~ x)` analysis of variance (same as `lm()` except in the summary)
- `gam(y ~ x)` generalized additive models
- `tree(y ~ x)` or `rpart(y ~ x)` regression/classification trees



[here!!](https://jhudatascience.org/tidyversecourse/model.html#data-needs){target="_blank"}


